name: "Vprofile IAC"
on:
    push:
        branches:
            - main
            - stage
        paths:
            -terraforms/**
    pull_request:
        branches:
            - main
        paths:
            - terraform/**

env:
AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
#REGISTRY

jobs:
    terraform:
        name: "apply teraform code chnages"
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: ./terraform
        
        steps:
            - name: Checkout source code
            - uses: actions/checkout@v4
              with:
                  sparse-checkout: .
            - name: setup terraform
            - uses: hashicorp/setup-terraform@v3
             




