name: "Vprofile IAC"
on:
    push:
        branches:
            - main
            - stage
        paths:
            -terraforms/**
    pull_request:
        branches:
            - main
        paths:
            - terraform/**

env:
AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY}}
#REGISTRY



